#
# Sample .travis.yml using the mvp-helloworld image (a helmoperator)
#
dist: trusty
sudo: required
group: bluezone
os:
  - linux

services:
  - docker

env:
  global:
    - OS=linux
    - COMPONENT_TYPE="helmoperator"
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
      name: "Build the image and run unit tests"
      script:
        - echo "no-op build"
        - make
        - make component/build
        - make component/push
    - stage: test
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        - echo "no-op deploy-and-test"
        - make
        - make component/pull
        - make component/test/unit
        # TODO: Checkout cluster and deploy
        # - make component/deploy
        - make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch IN ( master )
      script:
        - echo "no-op publish"
        - make
        # TODO: Make component manifest update not a no-op
        - make component/manifest/update
