#
# Sample .travis.yml using the mvp-helloworld image (a helmoperator)
#
dist: trusty
sudo: required
group: bluezone
os:
  - linux

services:
  - docker

env:
  global:
    - OS=linux
    - OPERATOR_SDK_VERSION=v0.15.0
    - COMPONENT_NAME_AND_TAG="mvp-helloworld-operator:1.0.0"

before_install:
    - curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu
    - chmod +x operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu

jobs:
  include:
    - stage: build
      name: "Build the image and run unit tests"
      script:
        - echo "no-op"
    - stage: deploy-and-test
      name: "Deploy the image to a cluster and run e2e tests"
      script:
        - ehco "no-op"
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      script:
        - echo "no-op"
