apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-operator
  annotations:
    metering.ibm.com/productID: test-busybox-helm-operator
    metering.ibm.com/productName: Test Busybox Helm Operator
    metering.ibm.com/productVersion: 1.0.0
    metering.ibm.com/productMetric: VIRTUAL_PROCESSOR_CORE
    metering.ibm.com/productChargedContainers: All
spec:
  replicas: 1
  selector:
    matchLabels:
      name: busybox-operator
  template:
    metadata:
      labels:
        name: busybox-operator
    spec:
      serviceAccountName: busybox-operator
      containers:
        - name: busybox-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "busybox-operator"
